version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current

    steps:
      - checkout

      # Récupérer les dépendances de l'application
      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build Docker image
          command: docker build -t my-node-app .

      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:8080 --name my-node-app my-node-app
            sleep 5 # Attendre que l'application démarre
      - run:
          name: Test if Docker container is running
          command: |
            curl --fail http://127.0.0.1:8080 || exit 1 # Tester la route principale ou de santé

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
